services:

  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}" ]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7.2-alpine
    ports:
      - "6379:6379"
    restart: unless-stopped
    volumes:
      - redis_data:/data
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli ping | grep PONG" ]
      interval: 5s
      timeout: 5s
      retries: 5

  mailhog:
    image: mailhog/mailhog:latest
    restart: unless-stopped
    environment:
      MH_STORAGE: maildir
      MH_MAILDIR_PATH: maildir
    ports:
      - "1025:1025"
      - "8025:8025"
    volumes:
      - mailhog_data:/home/mailhog/maildir
    healthcheck:
      test: [ "CMD", "echo | telnet 127.0.0.1 8025" ]
      interval: 1m30s
      timeout: 5s
      retries: 3

volumes:
  postgres_data:
  redis_data:
  mailhog_data:
